{
  "openapi":"3.0.2",
  "info": {
    "title":"API Title",
    "version":"1.0",
    "license": {
      "name": "MIT",
      "url": "https://github.com/DiegoVictor/ecoleta-api/blob/master/LICENSE"
    }
  },
  "servers": [
    {
      "url":"http://localhost:3333/v1"
    }
  ],
  "paths": {
    "/items": {
      "get": {
        "tags": ["items"],
        "responses": {
          "200": {
            "description": "Lists points' items.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Item"
                  }
                },
                "examples": {
                  "Items": {
                    "$ref": "#/components/examples/Items"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/points": {
      "get": {
        "tags": ["points"],
        "parameters": [
          {
            "in": "query",
            "name": "city",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "uf",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "items",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "1,2,3"
          }
        ],
        "responses": {
          "200": {
            "description": "Lists points",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Point"
                  }
                },
                "examples": {
                  "Points": {
                    "$ref": "#/components/examples/Points"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["points"],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "required": [
                  "name",
                  "email",
                  "whatsapp",
                  "latitude",
                  "longitude",
                  "city",
                  "uf",
                  "items",
                  "image"
                ],
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "whatsapp":  {
                    "type": "string"
                  },
                  "latitude":  {
                    "type": "number"
                  },
                  "longitude":  {
                    "type": "number"
                  },
                  "city":  {
                    "type": "string"
                  },
                  "uf":  {
                    "type": "string"
                  },
                  "items":  {
                    "type": "string"
                  },
                  "image":  {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Create a new point",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Point"
                },
                "example": {
                  "id": 1,
                  "image": "6f91cfcdd57d-baterias.svg",
                  "name": "Recyclus",
                  "email": "contact@recyclus.com",
                  "whatsapp": "551540331438",
                  "latitude": -23.5435933,
                  "longitude": -46.6366882,
                  "city": "São Paulo",
                  "uf": "SP",
                  "image_url": "http://localhost:3333/uploads/points/6f91cfcdd57d-baterias.svg"
                }
              }
            }
          }
        }
      }
    },
    },
  },
  "components": {
    "schemas": {
      "Item": {
        "properties": {
          "id": {
            "type": "integer"
          },
          "title": {
            "type": "string"
          },
          "image": {
            "type": "string"
          },
          "image_url": {
            "type": "string"
          }
        }
      },
      "Point": {
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "whatsapp": {
            "type": "string"
          },
          "latitude": {
            "type": "number"
          },
          "longitude": {
            "type": "number"
          },
          "city": {
            "type": "string"
          },
          "uf": {
            "type": "string"
          },
          "image": {
            "type": "string"
          },
          "image_url": {
            "type": "string"
          }
        }
      }
    },
    "examples": {
      "Items": {
        "value": [
          {
            "id": 1,
            "title": "Lâmpadas",
            "image": "lampadas.svg",
            "image_url": "http://localhost:3333/uploads/items/lampadas.svg"
          }
        ]
      },
      "Point": {
        "value": {
          "point": {
            "id": 1,
            "image": "6f91cfcdd57d-baterias.svg",
            "name": "Recyclus",
            "email": "contact@recyclus.com",
            "whatsapp": "551540331438",
            "latitude": -23.5435933,
            "longitude": -46.6366882,
            "city": "São Paulo",
            "uf": "SP",
            "image_url": "http://localhost:3333/uploads/points/6f91cfcdd57d-baterias.svg"
          },
          "items": [
            {
              "title": "Lâmpadas"
            },
            {
              "title": "Pilhas e baterias"
            }
          ]
        }
      },
      "Points": {
        "value": [
          {
            "id": 1,
            "image": "6f91cfcdd57d-baterias.svg",
            "name": "Recyclus",
            "email": "contact@recyclus.com",
            "whatsapp": "551540331438",
            "latitude": -23.5435933,
            "longitude": -46.6366882,
            "city": "São Paulo",
            "uf": "SP",
            "image_url": "http://localhost:3333/uploads/points/6f91cfcdd57d-baterias.svg"
          }
        ]
      }
    }
  }
}
